spring:
    datasource:
        url: jdbc:mysql://localhost:3307/jwt_security
        username: root
        password: Allawi2020
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
          hibernate:
              format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
    servlet:
        multipart:
            file-size-threshold:
                2KB
            max-file-size:
                50MB
            max-request-size:
                65MB
    mail:
        host: localhost
        port: 1025
        username: SourceFiles
        password: 123456
        properties:
          mail:
              smtp:
                  trust: "*"
              auth: true
              starttls:
                  enable: true
              connectiontimeout: 5000
              timeout: 3000
              writetimeout: 5000

application:
    mailing:
        frontend:
            activation-url: http://localhost:5173/activate-account
server:
    error:
        include-message: always

logging:
    file:
      name: application.log
    level:
        com.humam.security.aspect.FileUploadAspect: info
        com.humam.security.aspect.FileDownloadAspect: info
    logback:
        rollingpolicy:
            enabled: false



